import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Zen_Maru_Gothic } from "next/font/google";
import BottomNavigation from "@/components/ui/BottomNavigation";

const zenMaru = Zen_Maru_Gothic({
  subsets: ["latin"],
  weight: ["400", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${zenMaru.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  <div className="flex-1 pb-28">
    {children}
  </div>

  <BottomNavigation />
</body>
    </html>
  );
}
